export { default as About } from './about/About';
export { default as Cardexperience } from './cardexperience/Cardexperience';
export { default as Cardporject } from './cardprojects/Cardporject';
export { default as Contact } from './contact/Contact';
export { default as Experience } from './experience/Experience';
export { default as Footer } from './foter/Footer';
export { default as Header } from './header/Header';
export { default as HeroSection } from './heroSection/HeroSection';
export * from './index';
export { default as Intro } from './intro/Intro';
export { default as Main } from './main/Main';
export { default as Navigator } from './nav/Navigator';
export { default as Projects } from './porjects/Projects';
export { default as TableProjects } from './table/TableProjects';
